CardGame: Source.o Deck.o Card.o BJGame.o Player.o
	g++ Source.o Deck.o Card.o BJGame.o Player.o -o CardGame

Source.o: Source.cpp
	g++ -c Source.cpp

Deck.o: Deck.cpp
	g++ -c Deck.cpp

Card.o: Card.cpp
	g++ -c Card.cpp

BJGame.o: BJGame.cpp
	g++ -c BJGame.cpp

Player.o: Player.cpp
	g++ -c Player.cpp

